/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-14.glb -T
Files: macbook-14.glb [629.72KB] > /Users/adrianhajdin/Desktop/macbook_gsap_app/public/models/macbook-14-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-14-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 14 inch 2024
*/

import { useGLTF, useTexture } from '@react-three/drei';
import { useEffect } from 'react';
import { Color, Material, Mesh, Object3D, SRGBColorSpace } from 'three';
import type { GLTF } from 'three-stdlib';
import { noChangeParts } from "../../constants/index";
import useMacbookStore from "../../store";

interface MacbookModel14Props {
  scale?: number;
  position?: [number, number, number];
  rotation?: [number, number, number];
  dispose?: null;
}

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: Object3D;
  };
  materials: {
    [key: string]: Material;
  };
};

export default function MacbookModel14(props: MacbookModel14Props) {
  const { color } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF('/models/macbook-14-transformed.glb') as unknown as GLTFResult;

  const texture = useTexture('/screen.png');
  texture.colorSpace = SRGBColorSpace;
  texture.needsUpdate = true;

  useEffect(() => {
    scene.traverse((child: Object3D) => {
      if (child instanceof Mesh) {
        if (!noChangeParts.includes(child.name)) {
          child.material.color = new Color(color);
        }
      }
    });
  }, [color, scene]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Object_10 as Mesh).geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_16 as Mesh).geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_20 as Mesh).geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_22 as Mesh).geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_30 as Mesh).geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_32 as Mesh).geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_34 as Mesh).geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_38 as Mesh).geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_42 as Mesh).geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_48 as Mesh).geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_54 as Mesh).geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_58 as Mesh).geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_66 as Mesh).geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_74 as Mesh).geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_82 as Mesh).geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_96 as Mesh).geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_107 as Mesh).geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={(nodes.Object_123 as Mesh).geometry} rotation={[Math.PI / 2, 0, 0]} >
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh geometry={(nodes.Object_127 as Mesh).geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload('/models/macbook-14-transformed.glb');
